name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Build the Docker image
      run: |
        docker login docker.pkg.github.com --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
        docker build --pull --target php --tag "docker.pkg.github.com/$GITHUB_REPOSITORY/base-php" .
        docker build --pull --target nodejs --tag "docker.pkg.github.com/$GITHUB_REPOSITORY/base-node" .
        docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/base-php"
        docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/base-node"
